/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ChartsLazyImport = createFileRoute('/charts')()
const IndexLazyImport = createFileRoute('/')()
const AuthorsAuthorIdLazyImport = createFileRoute('/authors/$authorId')()

// Create/Update Routes

const ChartsLazyRoute = ChartsLazyImport.update({
  path: '/charts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/charts.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthorsAuthorIdLazyRoute = AuthorsAuthorIdLazyImport.update({
  path: '/authors/$authorId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/authors/$authorId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsLazyImport
      parentRoute: typeof rootRoute
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ChartsLazyRoute,
  AuthorsAuthorIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/charts",
        "/authors/$authorId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/charts": {
      "filePath": "charts.lazy.tsx"
    },
    "/authors/$authorId": {
      "filePath": "authors/$authorId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
